### ISSUE TITLE
WotLK: Missing cp bar and aura/spell mods

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#538]
**Description**:  
No xp bar is showing. No spell/aura mods as well.

**Steps to reproduce the problem**:
1.  Log in
2.  Create a new char
3.  Enter world

**Version**: WotLK

**AscEmu hash/commit**:  
b484fa65e7090b193153d1d3af661411666bd838

**Operating system**:  
Win10 / x64

**Comment by Evairfairy** [comment]
This was caused by incorrect data structs and is now resolved.

**Comment by Appled** [comment]
@Evairfairy XP bar is shown now correctly but auras/spells aren't still functioning. For instance, rank 1 pyroblast says in tooltip "causes 100-200 damage" but actually does 10-20 damage. Auras aren't shown when casted.
As well related to data structs, energy is not regening at all on rogue, but mana for instance on mage does regen.

**Comment by Appled** [comment]
Oh btw the auras actually function but just does not appear. For instance if I cast rank 1 fireball on a mob, I can see the dot dealing damage but just not appearing on target. Same with rogue's gouge, the mob is incapacitated for its duration but aura isn't shown.

**Comment by Zyres** [comment]
@Appled Can you retest it and close the issue if resolved?

**Comment by Appled** [comment]
Partially fixed. Auras work correctly now but the other issues still remain.
and I can't close issues 😄

**Comment by Appled** [comment]
I also tested health and power regening after data struct changes. Health and all powers besides energy on rogue regened and functioned properly.

**Comment by Zyres** [comment]
Last Point:
- [ ] energie regen
