### ISSUE TITLE
👾 [Bug Report] Dead at birth

### ISSUE THREAD

**Issue by armm77** [AscEmu/AscEmu#916]
**Description**: 
When creating the character and entering the game, he appears dead. 

**Steps to reproduce the problem**: 
1. Create  character of any faction or race. 
2. Enter the game. 

**Expansion version**: 
    Specify version - is required:
    - Patch 4.3.4 - Cataclysm

**AscEmu hash/commit**: 
https://github.com/AscEmu/AscEmu/commit/d013a56a6e0de8e2ae34a4da00760c79fbdc4c29

**Operating system**: 
    Specify the operating system - is required:
    - Platform: MacOSX
    - Platform: Windows

https://user-images.githubusercontent.com/3104815/132949434-64e6efd8-cda7-4cc1-be10-51cb1bc0b67f.mov

**Comment by schnek** [comment]
![image](https://user-images.githubusercontent.com/1216225/133659545-42157d73-5508-4d3d-8e01-03acba0ba6f4.png)
undead can't get up and lying down I raised lvl 3

**Comment by Zyres** [comment]
@armm77 Did you use the master or the develop branch?
@Appled You were able to reproduce the issue?

**Comment by armm77** [comment]
@Zyres i use the branch develop

**Comment by Zyres** [comment]
> @Zyres i use the branch develop

Can you retest with the latest dev: 733adb3dd9651ef02be58d534fce2039cc070896
Please set up Warning level as here:
![image](https://user-images.githubusercontent.com/8825392/133880377-bc0c79fe-373a-44ce-b459-fa8648e9518a.png)

Cleane your logfile and do it again, shutdown server and, if you want, you can send me the logfile for further investigation.

**Comment by Zyres** [comment]
@armm77 and @schnek  Should be solved now, please give feedback to latest dev if not.

**Comment by schnek** [comment]
1. at the first start the same way
![image](https://user-images.githubusercontent.com/1216225/133887143-91e93862-89d0-45ee-a570-58726cb8b9b8.png)
![image](https://user-images.githubusercontent.com/1216225/133887154-61306cf9-57b2-4520-a69f-300f779b75d1.png)
2. when exiting the game and re-entering it is normal
![image](https://user-images.githubusercontent.com/1216225/133887212-857800c4-a746-4b94-91cd-f7439f717e4e.png)

**Comment by schnek** [comment]
dump

**Comment by schnek** [comment]
@Zyres  the issue in the starting location is not resolved...

1. at the first start the same way
![image](https://user-images.githubusercontent.com/1216225/133887143-91e93862-89d0-45ee-a570-58726cb8b9b8.png)
![image](https://user-images.githubusercontent.com/1216225/133887154-61306cf9-57b2-4520-a69f-300f779b75d1.png)
2. when exiting the game and re-entering it is normal
![image](https://user-images.githubusercontent.com/1216225/133887212-857800c4-a746-4b94-91cd-f7439f717e4e.png)
maybe it will be useful
[dump-world.exe-b7ff096f7-2021-9-18-14-31-6-8512.zip](https://github.com/AscEmu/AscEmu/files/7189826/dump-world.exe-b7ff096f7-2021-9-18-14-31-6-8512.zip)

**Comment by Appled** [comment]
Reopened
